export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const LOADING_AUTHENTICATION = "LOADING_AUTHENTICATION";
export const LOADING_AUTHENTICATION_SUCCESS = "LOADING_AUTHENTICATION_SUCCESS";
export const LOADING_AUTHENTICATION_FAILED = "LOADING_AUTHENTICATION_FAILED";

